EzBooks Project/EzBooks_Site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('ez_main.urls')),
   path('accounts/', include('users.urls')),
]

EzBooks Project/ez_main/urls.py
###############################################################################
#                      Url Patterns for the ez_main app                       #
###############################################################################

from django.urls import path

from . import views

# Url patterns for the ez_main app
app_name = 'ez_main'
urlpatterns = [
   # Home page path
   path('', views.home_page, name='home_page'),

   # About page path
   path('about/', views.about_page, name='about_page'),

   # Class page path
   path('class/', views.class_page, name='class_page'),

   # Book page path
   path('books/', views.books_page, name='books_page'),
]

EzBooks Project/users/urls.py
###############################################################################
#                       Url Patterns for the users app                        #
###############################################################################

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
   # Login path
   path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

   # Register path
   path('register/', views.register, name='register'),

   # Logout path
   path('logout/', views.logout, name='logout'),
]

EzBooks Project/ez_main/models.py
###############################################################################
#                         Models for the ez_main app                          #
###############################################################################

from django.db import models
from users.models import *
from random import randint
from random import seed
from datetime import datetime

class Classes_list(models.Model):
   """ Complete list of all classes """
   class_name      = models.CharField(max_length=200)
   major           = models.CharField(max_length=100)
   class_extension = models.CharField(max_length=200)
   credit          = models.IntegerField(default=25)

   def __str__(self):
      """ Returning a string representation of the model """
      return self.class_name

   def display_classes(self, class1, class2, class3, class4, class5, class6):
      """ Get information for each class in a users class schedule """
      info1 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class1]) 
      info2 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class2])
      info3 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class3])
      info4 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class4])
      info5 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class5])
      info6 = Classes_list.objects.raw("select id, credit from main_db.ez_main_classes_list where class_name = %s limit 1", [class6])

      return info1[0], info2[0], info3[0], info4[0], info5[0], info6[0]

class Class_schedule(models.Model):
   """ Class schedule associated with each user """
   user_id = models.OneToOneField(User_profile ,on_delete=models.CASCADE, primary_key=True)
   class1  = models.CharField(max_length = 200,  null = True, blank = True)
   class2  = models.CharField(max_length = 200,  null = True, blank = True)
   class3  = models.CharField(max_length = 200,  null = True, blank = True)
   class4  = models.CharField(max_length = 200,  null = True, blank = True)
   class5  = models.CharField(max_length = 200,  null = True, blank = True)
   class6  = models.CharField(max_length = 200,  null = True, blank = True)

   def __str__(self):
      """ Returning a string representation of the model """
      return self.class1 + " - " + self.class2 + " - " + self.class3 + " - " + self.class4 + " - " + self.class5 + " - " + self.class6

   def create_class(self, major):
      """ Create a randomized class schedule based on major linked to a user """
      query_major = major
      random_classes = Classes_list.objects.raw("select id, class_name from main_db.ez_main_classes_list where major = %s order by rand() limit 6", [query_major])
      self.class1 = str(random_classes[0])
      self.class2 = str(random_classes[1])
      self.class3 = str(random_classes[2])
      self.class4 = str(random_classes[3])
      self.class5 = str(random_classes[4])
      self.class6 = str(random_classes[5])

      return random_classes

class Book_list(models.Model):
    """ Complete list of all the textbooks """
    department_name = models.CharField(max_length=200)
    course          = models.CharField(max_length=200)
    textbook        = models.CharField(max_length=200)
    edition         = models.CharField(max_length=200)
    isbn            = models.CharField(max_length=200)

    def __str__(self):
        """ Returning a string representation of the model """
        return self.textbook

class Books(models.Model):
   """ List of the books needed by each user """
   user_id           = models.ForeignKey(User_profile ,on_delete=models.CASCADE, primary_key=False)
   textbook_name     = models.CharField(max_length=200)
   used_rental_price = models.IntegerField(default=25)
   new_rental_price  = models.IntegerField(default=25)
   used_buy_price    = models.IntegerField(default=25)
   new_buy_priced    = models.IntegerField(default=25)
   # Course to which the book belongs??

   def __str__(self):
      """ Returning a string representation of the model """
      return self.textbook_name

   def find_books(self, extensions, user):
      """ Look up the textbooks needed for each class by class extension """
      page = Books() # Instantiate an instance of the books class
      all_books = [] # Empty list for all the textbook names

      # Loop through all class extensions, finding each book for the respective class
      for extension in extensions:
         for obj in Book_list.objects.raw("select id from main_db.ez_main_book_list where course = %s", [extension]):
            all_books.append(obj.textbook)

      # Remove any duplicate textbooks
      for book in all_books:
         # Check to see if there is more than one instance of each textbook
         if all_books.count(book) > 1:
            all_books.remove(book)

      # Save the final books list into the database with the appropriate data
      for book in all_books:
         seed(datetime.now())
         price = randint(50,350)
                  
         # Assign a price of zero to all the classes which do not require a textbook
         if book == 'NO TEXT REQUIRED':
            page = Books.objects.create(textbook_name = book, used_rental_price = 0, new_rental_price = 0, used_buy_price = 0, new_buy_priced = 0, user_id = user)
         else:
            page = Books.objects.create(textbook_name = book, used_rental_price = price / 3, new_rental_price = price / 2, used_buy_price = price * (2/3), new_buy_priced = price, user_id = user)

      return self

EzBooks Project/ez_main/views.py
###############################################################################
#                          Views for the ez_main app                          #
###############################################################################

from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import *

def home_page(request):
   """ Return the home page for ez_main """
   return render(request, 'ez_main/home_page.html')

def about_page(request):
   """ Return the about page for ez_main """
   return render(request, 'ez_main/about_page.html')

@login_required
def class_page(request):
   """ Return the users class schedule page """
   class_extensions = []  # Empty list used to store the class extensions
   book  = Books()        # Books object initialization
   user  = request.user   # Get the currently authenticated user
   no_books = True        # Flag value, assuming no books exist for a user

   class1  = user.class_schedule.class1
   class2  = user.class_schedule.class2
   class3  = user.class_schedule.class3
   class4  = user.class_schedule.class4
   class5  = user.class_schedule.class5
   class6  = user.class_schedule.class6
   classes = Classes_list()
   display_classes = classes.display_classes(class1, class2, class3, class4, class5, class6)

   # Check to see if books exist yet for a user
   for book in Books.objects.filter(user_id__pk=user.id)[:1]:
      no_books = False

   # Regenerate a new schedule based on the users major
   if request.method == 'POST':
      new_users_schedule = Class_schedule(user.id)
      new_users_schedule.create_class(user.major)
      new_users_schedule.save()       
      return HttpResponseRedirect(reverse('ez_main:class_page'))

   for obj in display_classes:
      class_extensions.append(obj.class_extension)

   # If no books exist for the user, get the users books based on classes
   if no_books:
      print("made the books!")
      book = book.find_books(class_extensions, user)

   return render(request, 'ez_main/class_page.html', {'display_classes': display_classes})

@login_required
def books_page(request):
   """ Return the users needed textbooks page """
   user_books = []      # Create an empty list for the users books
   user  = request.user # Get the currently authenticated user

   for book in Books.objects.filter(user_id__pk=user.id):
      user_books.append(book)

   return render(request, 'ez_main/books_page.html', {'user_books': user_books})

EzBooks Project/ez_main/templates/ez_main/about_page.html
{% extends "ez_main/base.html" %}

<!-- Uses the aboutpage_style.css file located in the ez_main app static folder -->

{% block content %}
<div id="wrapper" class="wrapper">

   <!-- Start Flipbox Style-->
   <div class="section-flipbox section-ptb-120">
      <div class="container">

         <div class="row">
            <!-- Start of Flipbox 1 -->
            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
               <div class="square-flip charity-flip">
                  <div class="square">
                     <div class="square-container">
                        <span>About</span>
                     </div>
                     <div class="flip-overlay"></div>
                  </div>

                  <div class="square2">
                     <div class="square-container2">
                        <h2>About Simple Scholar</h2>
                        <p>The goal of Simple Scholar is to provide a simple, and convenient method for you, as a busy student, to get your textbooks for the semester!</p>
                     </div>
                     <div class="flip-overlay"></div>
                  </div>
               </div>
            </div>
            <!-- End of Flipbox 1 -->

            <!-- Start of Flipbox 2 -->
            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
               <div class="square-flip charity-flip">
                  <div class="square">
                     <div class="square-container">
                        <span>The Team</span>
                     </div>
                     <div class="flip-overlay"></div>
                  </div>

                  <div class="square2">
                     <div class="square-container2">
                        <h2>The Simple Scholar Team</h2>
                        <p>Consisting of several college students who know all to well the experience of getting textbooks the hard way, the Simple Scholar team set out to solve these devastating stuggles for all future students.</p>
                     </div>
                     <div class="flip-overlay"></div>
                  </div>
               </div>
            </div>
            <!-- End of Flipbox 2 -->

            <!-- Start of Flipbox 3 -->
            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
               <div class="square-flip charity-flip">
                  <div class="square">
                     <div class="square-container">
                        <span>Services</span>
                     </div>
                     <div class="flip-overlay"></div>
                  </div>

                  <div class="square2">
                     <div class="square-container2">
                        <h2>Services</h2>
                        <p>Simple Scholar offers delivery of your textbook order directly to your dorm room. In addition, all orders are available for pickup at the MK Great Hall within 30 minutes of placing your order.</p>
                     </div>
                     <div class="flip-overlay"></div>
                  </div>
               </div>
            </div>
            <!-- End of Flipbox 3 -->

         </div>
      </div>
   </div>
   <!-- End Flipbox Style-->

   <!-- Additional info to help the users -->
   <div class="help-info">
      <p>
         &emsp;This website is intended to act as an additional tool for an
         existing college class registration system, to simulate this,
         we ask all users to select a major when they register for our website.
         The major you choose will then be used to randomly generate a mock
         class schedule for you. This mock schedule is a key element in order
         to demonstrate the true functionality of our website.
      </p>
   </div>
   
   <div class="help-info">
      <p>
         &emsp;After registering for our website, you will be shown your
         generated schedule, and given the option to regenerate your schedule
         if you wish. Once you confirm your schedule, you will be taken to the
         book selection page. Each book on this page is gathered according to the
         textbook needs of the classes in your schedule. Here you can choose to
         remove any books which you may already own, or have chosen to purchase
         elsewhere.
      </p>
   </div>
   
   <div class="help-info">
      <p>
         &emsp;Once you finish choosing which textbooks to order, you will be
         brought to the checkout page. On this page you will be given the
         option to rent or buy both new or used textbooks. After choosing your
         textbook purchasing preferences, you will be asked if you would like to
         have your order either picked up or delivered. Once you confirm your order
         you will move one to the payment process after that you are done!
      </p>
   
      <a class="btn btn-primary btn3d" id="start-btn" href="{% url 'users:register' %}">Get Started!</a>
   
   </div>

</div>

{% endblock content %}

EzBooks Project/ez_main/templates/ez_main/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>

      <title>Simple Scholar</title>

      <!-- Bootstrap CSS stylesheet -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>

      <!-- JQuery and JS For Bootstrap -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

      <!-- Stylesheets for the web pages -->
      {% load static %}
      <link href="{% static "ez_main/base_style.css" %}" rel="stylesheet"/>
      <link href="{% static "ez_main/aboutpage_style.css" %}" rel="stylesheet"/>
      <link href="{% static "ez_main/modal_style.css" %}" rel="stylesheet"/>
      <link href="{% static "ez_main/home_styles.css" %}" rel="stylesheet"/>
      <!-- <link href="{% static "ez_main/plugins.css" %}" rel="stylesheet"/> -->
        
   </head>

<body>
   <!-- Navbar displayed at all times on the project -->
   <!-- Uses the base_styles.css file (Global styles for the pages are in this file as well) -->
   <nav class="navbar-nav navbar-expand-lg bg-dark navbar-dark">
      <a class="navbar-brand" href="{% url 'ez_main:home_page' %}">EzBooks</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
        
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="side-navbar-nav navbar-nav ml-auto">
         <!-- Display certain navbar links only when the user is logged in -->
         {% if user.is_authenticated %}
            <li class="nav-item">
               <p>Hello, &nbsp; {{ user.username }}.</p>
            </li>
            <li class="nav-item">
               <div class="dropdown">
                  <button class="btn btn-primary btn3d" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Personal Info</button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                     <a class="dropdown-item" href="{% url 'ez_main:class_page' %}">Your Schedule</a>
                     <a class="dropdown-item" href="{% url 'ez_main:books_page' %}">Your Books</a>
                  </div>
               </div>
            </li>
            <li class="nav-item">
               <a class="main-btn btn btn-primary btn3d" href="{% url 'users:logout' %}">Log out</a>
            </li>
         {% else %}
            <li class="nav-item">
               <a class="main-btn btn btn-primary btn3d" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
               <a class="main-btn btn btn-primary btn3d" href="{% url 'users:register' %}">Register</a>
            </li>
         {% endif %}
            <li class="nav-item">
               <a class="main-btn btn btn-primary btn3d" id="last" href="#">Shopping Cart</a>
            </li>
         </ul>
      </div>
   </nav>

   <!-- Container for content loaded with the project views -->
   <div class="content-wrap">
      <div class="body-content">
         <div class="page-header">
            {% block header%}{% endblock header %}
         </div>

         <div class="page-content">
            {% block content %}{% endblock content %}
         </div>
      </div>

      <!-- Global website Footer -->
      <footer class="page-footer">
         <!-- Footer Links -->
         <div class="container-fluid text-center text-md-left">
            <div class="row">
               <div class="col-md-3 mb-md-0 mb-3">
                  <!-- 1st Column Links -->
                  <h5 class="text-uppercase">Additional Information</h5>
                  <ul class="list-unstyled">
                     <li>
                        <a href="{% url 'ez_main:about_page' %}">About</a>
                     </li>
                     <li>
                        <a href="#!">Contact Info</a>
                     </li>
                  </ul>
               </div>

               <div class="col-md-3 mb-md-0 mb-3">
                  <!-- 2nd Column Links -->
                  <h5 class="text-uppercase">Join Simple Scholar</h5>
                  <ul class="list-unstyled">
                     <li>
                        <a href="{% url 'users:login' %}">Login</a>
                     </li>
                     <li>
                        <a href="{% url 'users:register' %}">Register</a>
                     </li>
                  </ul>
               </div>

               <div class="col-md-3 mb-md-0 mb-3">
                  <!-- 3rd Column Links -->
                  <h5 class="text-uppercase">Even more links</h5>
                  <ul class="list-unstyled">
                     <li>
                        <a href="#">Stuff</a>
                     </li>
                     <li>
                        <a href="#">Shopping Cart</a>
                     </li>
                  </ul>
               </div>
            </div>
         </div>

         <div class="footer-copyright text-center py-3">
            <p>© 2019 Copyright: Ezbooks</p>
         </div>
      </footer>

   </div>

</body>
</html>

EzBooks Project/ez_main/templates/ez_main/books_page.html
{% extends "ez_main/base.html" %}

<!-- No specific style sheet for the books page -->

{% block content %}

   <div class="modal-dialog text-center">
      <div class= "main-section">
         <div class="modal-content">
            <h4>Required Textbooks for {{user.username}}</h4>
            <br />
         </div>
      </div>
   </div>
   
   <div class="modal-dialog">
      <table class="table">
         <thead class="thead-dark">
            <tr>
               <th class="text-white bg-dark" scope="col">Textbook Name</th>
               <th class="text-white bg-dark" scope="col">New Purchase Price</th>
               <th class="text-white bg-dark" scope="col">Used Purchase Price</th>
               <th class="text-white bg-dark" scope="col">New Rental Price</th>
               <th class="text-white bg-dark" scope="col">Used Rental Price</th>
               <th class="text-white bg-dark" scope="col"></th>

            </tr>
         </thead>
         <tbody>
            {% for obj in user_books %}
            <tr class="table-success">
               <td>{{obj.textbook_name}}</td>
               <td>{{obj.new_buy_priced}}</td>
               <td>{{obj.used_buy_price}}</td>
               <td>{{obj.new_rental_price}}</td>
               <td>{{obj.used_rental_price}}</td>
               <td><a class="btn btn-primary btn3d" href="#">Delete</a></td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
   </div>

{% endblock content %}

EzBooks Project/ez_main/templates/ez_main/class_page.html
{% extends "ez_main/base.html" %}

<!-- Uses the modal_style.css file (located in the ez_main app static folder) -->

{% block content %}

<!-- Bootstrap modal box for the class schedule -->
<div class="modal-dialog text-center">
   <div class= "main-section">
      <div class="modal-content">
         <h4>Class Schedule for {{user.username}}</h4>
         <p>Your major is: &nbsp; {{user.major}}</p>
         <br />
      </div>
   </div>
</div>

<div class="modal-dialog">
   <table class="table">
      <thead class="thead-dark">
         <tr>
            <th class="text-white bg-dark" scope="col">Extension</th>
            <th class="text-white bg-dark" scope="col">Class Name</th>
            <th class="text-white bg-dark" scope="col">Credit Hrs</th>
         </tr>
      </thead>
      <tbody>
         {% for obj in display_classes %}
         <tr class="table-success">
            <td>{{obj.class_extension}}</td>
            <td>{{obj.class_name}}</td>
            <td id="credit">{{obj.credit}}</td>
         </tr>
         {% endfor %}
      </tbody>
   </table>
</div>

<form method="post" action="{% url 'ez_main:class_page' %}" class="form">
   {% csrf_token %}
      <button name="submit" class="btn btn-primary btn3d">Try A Different Schedule</button>

      <input type="hidden" name="next" value="{% url 'ez_main:class_page' %}"/>
   </form>

<a class="btn btn-primary btn3d" href="{% url 'ez_main:books_page' %}">Confirm Your Schedule</a>

{% endblock content %}

EzBooks Project/ez_main/templates/ez_main/home_page.html
{% extends "ez_main/base.html" %}

<!-- Uses the home_styles.css file (located in the ez_main app static folder) -->

{% block content %}
<div class="homepage-info">
   <h1>Welcome to Simple Scholar!</h1>

   <p>
      <br />
      This website will help you to order your textbooks according to
      your class schedule and the books required for those classes.
   </p>
</div>

<!-- Modal containing homepage navigation links -->
<div class="modal-dialog text-center">
   <div class="col-sm-8 main-section home-modal">
      <div class="modal-content">
         <div class="col-12">
            <a class="btn btn-primary btn3d home-btn" href="{% url 'users:register' %}">Get Started Now!</a>
            <a class="btn btn-primary btn3d home-btn" href="{% url 'ez_main:about_page' %}">Get Started With Some Help!</a>
         </div>
      </div>
   </div>
</div>

{% endblock content %}